AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Template for cloudwatch-alert-macro

Resources:
  AlarmMacro:
   Type: AWS::CloudFormation::Macro
   Properties:
     Name: AlarmMacro
     FunctionName: !GetAtt AlarmMacroFunction.Arn

  AlarmMacroFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: "AlarmMacroFunction"
      Description: "Lambda Function for Alarm macro that appends alarms to specified resources in cloudformation templates"
      Handler: "alarm_macro.handler"
      MemorySize: 128
      Runtime: "python3.6"
      Timeout: 60
      CodeUri: ./src
      Policies:
      - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          SNSTopic: arn:aws:sns:us-east-1:713147272639:monitorBottleLambdaBottleIOT #Replace it with your own SNSTopic ARN